export type {
  DuplicateDetectionPort,
  IdentityResolutionPort,
  MedicalRecordsNotificationPort,
  PatientApplicationDependencies,
  PatientApplicationEventPublisher,
  PatientApplicationOperation,
  PatientAuditPort,
  PatientAuditRecord,
  PatientAuthorizationPort,
  PatientIdentifierUniquenessPort,
  PatientIdentityReference,
  PatientNotification,
  PatientNotificationPort,
  PatientRepository,
  PatientRestorationPort,
  PatientSearchCriteria,
  PatientSearchPort,
  PatientTimelineEntry,
  PatientTimelinePort,
  MedicalRecordsPatientNotification,
} from './patient.ports';
